<?php

declare(strict_types=1);

return [
    'brands' => [
        'Abarth',
        'Acura',
        'Alfa Romeo',
        'Alpina',
        'Aston Martin',
        'Audi',
        'Bentley',
        'BMW',
        'Bugatti',
        'Buick',
        'Cadillac',
        'Caterham',
        'Changan',
        'Chery',
        'Chevrolet',
        'Chrysler',
        'Citroën',
        'Dacia',
        'Dodge',
        'Donkervoort',
        'DS Automobiles',
        'Ferrari',
        'Fiat',
        'Ford',
        'GAZ',
        'Geely',
        'GMC',
        'Great Wall',
        'Gumpert',
        'Haval',
        'Honda',
        'Hummer',
        'Hyundai',
        'Infiniti',
        'JAC',
        'Jaguar',
        'Jeep',
        'Kia',
        'Koenigsegg',
        'Lada',
        'Lamborghini',
        'Lancia',
        'Land Rover',
        'Lexus',
        'Lincoln',
        'Lotus',
        'Maserati',
        'Mazda',
        'McLaren',
        'Mercedes-Benz',
        'Mini',
        'Mitsubishi',
        'Morgan',
        'Nissan',
        'Opel',
        'Pagani',
        'Peugeot',
        'Pontiac',
        'Porsche',
        'Ram',
        'Renault',
        'Rolls-Royce',
        'Seat',
        'Skoda',
        'Smart',
        'Spyker',
        'SsangYong',
        'Subaru',
        'Suzuki',
        'Tesla',
        'Toyota',
        'TVR',
        'UAZ',
        'Volkswagen',
        'Volvo',
        'Wiesmann',
        'ZAZ',
    ],
    'gas_station_logos' => [
        'shell' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shell_logo.svg/1200px-Shell_logo.svg.png',
        'bp' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/BP_Helios_logo.svg/1200px-BP_Helios_logo.svg.png',
        'aral' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Aral_Logo.svg/1200px-Aral_Logo.svg.png',
        'total' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'totalenergies' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'tamoil' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Tamoil.svg/2560px-Tamoil.svg.png',
        'esso' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Esso_textlogo.svg/2560px-Esso_textlogo.svg.png',
        'tango' => 'https://www.tango.nl/themes/custom/tango_subtheme/logo.svg',
        'q8' => 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Q8_logo.png',
        'eni' => 'https://upload.wikimedia.org/wikipedia/it/thumb/8/8a/Logo_ENI.svg/490px-Logo_ENI.svg.png',
        'agip' => 'https://i0.wp.com/moovingmedia.com/wp-content/uploads/2023/07/agip_2.png?fit=1040%2C1040&ssl=1',
        'kuster' => 'https://intermontage.nl/wp-content/uploads/Kuster_logo.png',
        'jet' => 'https://1000logos.net/wp-content/uploads/2022/07/Jet-Logo-2003.png',
        'makro' => 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Makro_Europe_logo.png',
        'tinq' => 'https://www.tinq.nl/sites/default/files/logo_0.png',
        'omv' => 'https://w7.pngwing.com/pngs/5/80/png-transparent-omv-hd-logo-thumbnail.png',
        'cirklek' => 'https://1000logos.net/wp-content/uploads/2020/11/Circle-K-Logo.png',
        'repsol' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Repsol_logo.svg/2560px-Repsol_logo.svg.png',
        'avia' => 'https://cdn.freebiesupply.com/logos/large/2x/avia-5-logo-png-transparent.png',
        'texaco' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Texaco_logo.svg/2560px-Texaco_logo.svg.png',
        'argos' => 'https://w7.pngwing.com/pngs/405/567/png-transparent-argos-energies-texaco-filling-station-tamoil-service-in-place-blue-text-trademark-thumbnail.png',
        'default' => 'https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_local_gas_station_48px-512.png',

    ],
];
