<?php

declare(strict_types=1);

return [
    'brands' => [
        "Abarth",
        "Acura",
        "Alfa Romeo",
        "Alpina",
        "Aston Martin",
        "Audi",
        "Bentley",
        "BMW",
        "Bugatti",
        "Buick",
        "Cadillac",
        "Caterham",
        "Changan",
        "Chery",
        "Chevrolet",
        "Chrysler",
        "Citroën",
        "Dacia",
        "Dodge",
        "Donkervoort",
        "DS Automobiles",
        "Ferrari",
        "Fiat",
        "Ford",
        "GAZ",
        "Geely",
        "GMC",
        "Great Wall",
        "Gumpert",
        "Haval",
        "Honda",
        "Hummer",
        "Hyundai",
        "Infiniti",
        "JAC",
        "Jaguar",
        "Jeep",
        "Kia",
        "Koenigsegg",
        "Lada",
        "Lamborghini",
        "Lancia",
        "Land Rover",
        "Lexus",
        "Lincoln",
        "Lotus",
        "Maserati",
        "Mazda",
        "McLaren",
        "Mercedes-Benz",
        "Mini",
        "Mitsubishi",
        "Morgan",
        "Nissan",
        "Opel",
        "Pagani",
        "Peugeot",
        "Pontiac",
        "Porsche",
        "Ram",
        "Renault",
        "Rolls-Royce",
        "Seat",
        "Skoda",
        "Smart",
        "Spyker",
        "SsangYong",
        "Subaru",
        "Suzuki",
        "Tesla",
        "Toyota",
        "TVR",
        "UAZ",
        "Volkswagen",
        "Volvo",
        "Wiesmann",
        "ZAZ",
    ],
];
