<?php

declare(strict_types=1);

return [
    'gas_station_logos' => [
        'shell' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shell_logo.svg/1200px-Shell_logo.svg.png',
        'shellexpress' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shell_logo.svg/1200px-Shell_logo.svg.png',
        'shellrecharge' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shell_logo.svg/1200px-Shell_logo.svg.png',
        'newmotion' => 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shell_logo.svg/1200px-Shell_logo.svg.png',
        'bp' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/BP_Helios_logo.svg/1200px-BP_Helios_logo.svg.png',
        'bpexpress' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/BP_Helios_logo.svg/1200px-BP_Helios_logo.svg.png',
        'bppulse' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/BP_Helios_logo.svg/1200px-BP_Helios_logo.svg.png',
        'aral' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Aral_Logo.svg/1200px-Aral_Logo.svg.png',
        'aralpulse' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Aral_Logo.svg/1200px-Aral_Logo.svg.png',
        'total' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'totalenergies' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'totalexpress' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'totalenergiesexpress' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'totalaccess' => 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png',
        'tamoil' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Tamoil.svg/2560px-Tamoil.svg.png',
        'esso' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Esso_textlogo.svg/2560px-Esso_textlogo.svg.png',
        'essoexpress' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Esso_textlogo.svg/2560px-Esso_textlogo.svg.png',
        'exxon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Exxon_logo_2016.svg/2560px-Exxon_logo_2016.svg.png',
        'exxonmobil' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Exxon_Mobil_Logo.svg/2560px-Exxon_Mobil_Logo.svg.png',
        'tango' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzey7KWG2WzAAssBLGmJRwWTekYBZQq72KkA&s',
        'q8' => 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Q8_logo.png',
        'eni' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Logo_ENI.svg/490px-Logo_ENI.svg.png',
        'agip' => 'https://i0.wp.com/moovingmedia.com/wp-content/uploads/2023/07/agip_2.png?fit=1040%2C1040&ssl=1',
        'kuster' => 'https://intermontage.nl/wp-content/uploads/Kuster_logo.png',
        'jet' => 'https://1000logos.net/wp-content/uploads/2022/07/Jet-Logo-2003.png',
        'makro' => 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Makro_Europe_logo.png',
        'tinq' => 'https://www.tinq.nl/sites/default/files/logo_0.png',
        'omv' => 'https://cdn.worldvectorlogo.com/logos/omv.svg',
        'cirklek' => 'https://1000logos.net/wp-content/uploads/2020/11/Circle-K-Logo.png',
        'repsol' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Repsol_logo.svg/2560px-Repsol_logo.svg.png',
        'avia' => 'https://cdn.freebiesupply.com/logos/large/2x/avia-5-logo-png-transparent.png',
        'texaco' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Texaco_logo.svg/2560px-Texaco_logo.svg.png',
        'argos' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Argos_Logo.svg/1200px-Argos_Logo.svg.png',
        'eko' => 'https://m.helpe.gr/userfiles/8a53b155-76e9-4d45-9773-a27000e44a36/EKO_logo_final.png',
        'ok' => 'https://ok.nl/app/uploads/sites/5/2020/04/ok-square.png',
        'berkman' => 'https://rotterdamcharityclub.nl/wp-content/uploads/2020/03/berkman.png',
        'lukoil' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/LUK_OIL_Logo.svg/2051px-LUK_OIL_Logo.svg.png',
        'dcb' => 'https://dcbenergy.nl/app/uploads/2024/04/favicon-512x512-1.png',
        'dcbenergy' => 'https://dcbenergy.nl/app/uploads/2024/04/favicon-512x512-1.png',
        'fastned' => 'https://content.presspage.com/uploads/2519/71bc054d-a4f9-47f4-bc66-8e1b12d9c540/800_1.mainfastnedlogoyellowbrown.png',
        'tesla' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Tesla_logo.png/600px-Tesla_logo.png',
        'teslasupercharger' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Tesla_logo.png/600px-Tesla_logo.png',
        'ionity' => 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Ionity_logo_cmyk.svg',
        'allego' => 'https://d1io3yog0oux5.cloudfront.net/_daf36d7642631fdb3a2380014d79eb54/allego/logo.png',
        'evbox' => 'https://d21buns5ku92am.cloudfront.net/68025/images/421521-EVBox%20Logo%20Black-8f3465-large-1647418113.png',
        'vattenfall' => 'https://www.ipkw.nl/wp-content/uploads/2020/10/ipkw-bedrijven-vattenfall-logo.png',
        'engie' => 'https://assets.design.digital.engie.com/brand/logo-primary.jpg',
        'lastmilesolutions' => 'https://openchargealliance.org/wp-content/uploads/2023/12/LMS-Logo-Stacked-Black-Blue@3x.png',
        'default' => 'https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_local_gas_station_48px-512.png',
    ],
];
