<?php

declare(strict_types=1);

return [
    'brands' => [
        'Acura',
        'Alfa Romeo',
        'Aston Martin',
        'Audi',
        'Bentley',
        'BMW',
        'Bugatti',
        'Cadillac',
        'Chevrolet',
        'Chrysler',
        'Citroën',
        'Dacia',
        'DS Automobiles',
        'Ferrari',
        'Fiat',
        'Ford',
        'Honda',
        'Hyundai',
        'Infiniti',
        'Jaguar',
        'Jeep',
        'Kia',
        'Koenigsegg',
        'Lada',
        'Lamborghini',
        'Land Rover',
        'Maserati',
        'Mazda',
        'McLaren',
        'Mercedes-Benz',
        'Mini',
        'Mitsubishi',
        'Nissan',
        'Opel',
        'Peugeot',
        'Porsche',
        'Ram',
        'Renault',
        'Rolls-Royce',
        'Seat',
        'Skoda',
        'Smart',
        'Subaru',
        'Suzuki',
        'Tesla',
        'Toyota',
        'Volkswagen',
        'Volvo',
    ],
];
